version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: kegesch-calibre-web_server_1
      APP_PORT: 8083
      PROXY_AUTH_ADD: "false"
    container_name: kegesch-calibre-web_app_proxy_1
  server:
    image: ghcr.io/kegesch/umbrel-apps/kegesch-calibre-web:0.6.25
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/books:/books
    restart: on-failure
    container_name: kegesch-calibre-web_server_1
